- hosts: all
  gather_facts: true
  become: true
  tasks:
  # Install/uninstall with chocolatey
  - name: Ensure 7-Zip is installed via Chocolatey
     win_chocolatey:
       name: 7zip
       state: present

  - name: Ensure 7-Zip is not installed via Chocolatey
     win_chocolatey:
      name: 7zip
      state: absent

