- name: teste
  hosts: all
  #gather_facts: true
  #connection: local
  tasks:
        - name: Stop service
          win_service:
            name: Zabbix Agent
            state: stopped
          register: output
        - debug:
                 msg : "{{output}}"

        - name: Change Server
          win_lineinfile:
            path: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'
            regex: '^Server='
            line: 'Server={{ Server_string }}'
          register: output2
          when: Server_string is defined
        - debug:
                msg : "{{output2}}"

        - name: Change ServerActive
          win_lineinfile:
            path: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'
            regex: '^ServerActive='
            line: 'ServerActive={{ ServerActive_string }}'
          register: output5
          when: ServerActive_string is defined
        - debug:
                msg : "{{output5}}  {{ ServerActive_string }}"


        - name: Change hostname
          win_lineinfile:
            path: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'
            regex: '^Hostname='
            line: 'Hostname={{ ansible_hostname|lower }}'
          register: output3
          when: Server_hostname is defined

        - debug:
                msg : "{{output3}}"
        - name: Start service
          win_service:
            name: Zabbix Agent
            state: started
          register: output4
        - debug:
                 msg : "{{output4}}"




