- hosts: all
  gather_facts: true
  #become: true
  connection: local
  tasks:
    - name: Restart a service
      win_service:
        name: "zabbix agent"
        state: stopped
    - name:  Troca o valor do server no arquivo do zabbix
      community.windows.win_lineinfile:
      path: c:\temp\zabbix_agentd.conf
      regexp: '^Server='
      line: 'Server= "Alterou a linha"'
      register: output
    - debug:
         var: output.stdout_lines


