- name: teste
  hosts: 127.0.0.1
  gather_facts: true
  connection: local
  tasks:
    - name: Run a cmd.exe command
      community.windows.psexec:
         #hostname: "192.168.100.11"
         hostname: "{{ inventory_hostname }}"
         connection_username: "{{ ansible_user }}"
         connection_password: "{{ ansible_password }}"
         executable: powershell
         arguments: -Command {set-executionpolicy -executionpolicy remotesigned;winrm set winrm/config/service '@{AllowUnencrypted="true"}'}
      register: output
    - debug:
           msg : "{{output}}"
    - name: Run a cmd.exe command
      community.windows.psexec:
         #hostname: "192.168.100.11"
         hostname: "{{ inventory_hostname }}"
         connection_username: "{{ ansible_user }}"
         connection_password: "{{ ansible_password }}"
         executable: powershell
         arguments: -Command {winrm quickconfig -q;winrm set winrm/config/service '@{AllowUnencrypted="true"}';winrm set winrm/config/service/auth '@{Basic="true"}'}
      register: output2
    - debug:
           msg : "{{output2}}"

