- hosts: localhost
  gather_facts: true
  #become: true
  connection: local
  tasks:
    - name: Run a cmd.exe command
      community.windows.psexec:
        hostname: {{ host_name }}
        connection_username: {{ user_name }}
        connection_password: {{ user_pass }}
        executable: cmd.exe
        arguments: /c echo Hello World
      register: output
    - debug:
         var: output.stdout_lines


