- hosts: all
  gather_facts: true
  #become: true
  tasks:
    - name: Run a cmd.exe command
      community.windows.psexec:
        hostname:192.168.0.99
        connection_username: wagnero
        connection_password: $Pantera01
        executable: cmd.exe
        arguments: /c echo Hello World
      register: output
    - debug:
         var: output.stdout_lines


