- hosts: all
  ansible_user: wagnero@corp.psoft
  ansible_password: $Pantera01
  ansible_connection: winrm
  ansible_port: 5985
  ansible_winrm_transport: kerberos
  gather_facts: true
  #become: true
  tasks:
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: C:\Temp\foo.conf
      state: touch
      become: true

